apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mini-recsys-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mini-recsys-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
