apiVersion: v1
kind: Service
metadata:
  name: mini-recsys
  labels:
    app: mini-recsys
spec:
  type: ClusterIP
  selector:
    app: mini-recsys
  ports:
    - name: http
      port: 80
      targetPort: http
